services:
  db:
    image: postgres:15-alpine
    container_name: orienteering_db_prod
    restart: always
    env_file:
      - ./db.env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  backend:
    image: ghcr.io/athamour1/oriento/backend:latest
    container_name: orienteering_backend_prod
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.prod

  frontend:
    image: ghcr.io/athamour1/oriento/frontend:latest
    container_name: orienteering_frontend_prod
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://your-domain.com

volumes:
  postgres_data_prod:
